[package]
name = "bubble_gw_benchmarks"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bubble_gw = { path = "../bubble-gw" }
criterion = {version = "0.8.1", features = ["html_reports"]}
ndarray = {workspace = true}
num-traits = {workspace = true}
puruspe = "0.4.2"
rand = "0.9.2"
scirs2-special = "0.1.0-rc.4"

[[bench]]
name = "integrate_1d"
path = "integrate_1d.rs"
harness = false

[[bench]]
name = "bulk_flow_bench"
path = "bulk_flow_bench.rs"
harness = false

[[bench]]
name = "first_bubble_bench"
path = "first_bubble_bench.rs"
harness = false

[[bench]]
name = "jn_puruspe_vs_scirs2"
path = "jn_puruspe_vs_scirs2.rs"
harness = false
