[project]
name = "pygw-fopt"
version = "0.1.0"
description = "Fast gravitational wave calculation from bubble collisions in first-order phase transitions"
license = { text = "MIT OR Apache-2.0" }
readme = "README.md"
authors = [
    { name = "hoquoctrung", email = "hoquoctrung98@gmail.com" }
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering :: Physics",
]
requires-python = ">=3.11"
dependencies = [
    "cosmotransitions>=2.0.7",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "maturin>=1.9.5",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "polars>=1.34.0",
    "psweep>=0.13.0",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
    "pyqt6>=6.9.1",
    "ipympl>=0.9.7",
    "h5py>=3.15.1",
    "pyyaml>=6.0.3",
    "bubble-gw-py",
]
[build-system]
requires = ["uv_build>=0.9.5"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "src/bubble_gw",
]

[tool.uv.sources]
bubble-gw-py = { workspace = true, editable = true }
