[project]
name = "pygw-fopt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hoquoctrung", email = "hoquoctrung98@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "cosmotransitions>=2.0.7",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "maturin>=1.9.5",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "polars>=1.34.0",
    "psweep>=0.15.0",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
    "bubble_gw_py @ file:///${PROJECT_ROOT}/src/bubble_gw",
    "pyqt6>=6.9.1",
    "ipympl>=0.9.7",
]

[build-system]
requires = ["uv_build>=0.8.23,<0.9.0"]
build-backend = "uv_build"
