[project]
name = "bubble-dynamics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hoquoctrung", email = "hoquoctrung98@gmail.com" }
]
dependencies = [
    "cosmotransitions>=2.0.7",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "maturin>=1.9.5",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "polars>=1.34.0",
    "psweep>=0.13.0",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
    # "pyqt6>=6.9.1",
    "ipympl>=0.9.7",
    "h5py>=3.15.1",
    "pyyaml>=6.0.3",
    "pyarrow>=22.0.0",
]

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"
