[workspace]
members = [
    "bubble_gw_rs",
    "benches",
    "bubble_gw_py",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Quoc Trung Ho <hoquoctrung98@gmail.com>"]
description = "Rust package for computing Gravitational Waves background from First Order Phase Transition"
readme = "README.md"
license="MIT"
rust-version = "1.86"

[workspace.dependencies]
ndarray = {version = "0.17.1", features = ["rayon", "approx"]}
num-complex = "0.4.6"
num = "0.4.3"
num-traits = "0.2.19"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
incremental = true

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3
incremental = true
