# use spaces instead of tabs
hard_tabs = false

# group imports and format them alphabetically
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# use trailing commas where appropriate (cleaner diffs)
trailing_comma = "Vertical"
match_block_trailing_comma = true

# always format imports and struct fields vertically when long
imports_granularity = "Module"
struct_field_align_threshold = 0

# force consistent indentation and alignment
indent_style = "Block"
fn_call_width = 80

wrap_comments = false
format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"

use_field_init_shorthand = true

condense_wildcard_suffixes = true
edition = "2024"
