[package]
name = "bubble-gw-python"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "bubble_gw_python"
crate-type = ["cdylib", "lib"]

[dependencies]
ndarray = {workspace = true}
nalgebra = {workspace = true}
num-complex = {workspace = true}
num = {workspace = true}
bubble_gw = { path = "../bubble-gw" }
pyo3 = { version = "0.27", features = ["extension-module", "num-complex", "experimental-inspect"] }
numpy = {version = "0.27.1", features = ["nalgebra"]}
thiserror = "2.0.17"
csv = "1.4.0"

[build-dependencies]
pyo3-build-config = "0.27"
