[workspace]
members = [
  "crates/*",
]
default-members = [
  "crates/bubble-gw",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Quoc Trung Ho <hoquoctrung98@gmail.com>"]
description = "Rust package for computing Gravitational Waves background from First Order Phase Transition"
readme = "README.md"
license="MIT OR Apache-2.0"
rust-version = "1.86"

[workspace.dependencies]
ndarray = {version = "0.17.2", features = ["rayon", "approx"]}
nalgebra = "0.33.2"
num-complex = "0.4.6"
num = "0.4.3"
num-traits = "0.2.19"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
incremental = true

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3
incremental = true
