[project]
name = "bubble-gw"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[tool.maturin]
profile = "release"
features = ["pyo3/extension-module"]
manifest-path = "crates/py-bubble-gw/Cargo.toml"
# manifest-path = "../Cargo.toml" 
# python-source = "python"
# module-name = "gw_fopt.py_bubble_gw"
module-name = "gw_fopt.bubble_gw.py_bubble_gw"
python-source = "python/src"

[tool.uv]
cache-keys = [{file = "pyproject.toml"}, {file = "Cargo.toml"}, {file = "../**/*.rs"}, {file = "**/*.py"}]
